---

version: 2

before:
  hooks:
    - go tool templ generate
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - sh -c 'go run . completion "bash" >./completions/{{ .ProjectName }}.bash'
    - sh -c 'go run . completion "zsh" >./completions/{{ .ProjectName }}.zsh'
    - sh -c 'go run . completion "fish" >./completions/{{ .ProjectName }}.fish'

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    main: .
    binary: adfinis-rclone-mgr
    ldflags:
      - -s
      - -w
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -X main.Date={{ .Date }}
      - -X main.BuiltBy=goreleaser
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: default
    name_template: "adfinis-rclone-mgr-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    ids:
      - default
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - completions/*


checksum:
  name_template: "checksums.txt"

nfpms:
  - file_name_template: "adfinis-rclone-mgr-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    vendor: adfinis
    homepage: "https://github.com/adfinis/adfinis-rclone-mgr"
    maintainer: "jonahz <jonah.zuercher@adfinis.com>"
    description: "Configure rclone mounts for Google Drive"
    license: "GPLv3"
    formats:
      - deb
      - rpm
      - archlinux
    dependencies:
      - rclone
      - nautilus-python
      - xclip
      - zenity
    conflicts:
      - adfinis-rclone-mount
    contents:
      - src: ./assets/adfinis-rclone-mgr@.service
        dst: /usr/lib/systemd/user/adfinis-rclone-mgr@.service
      - src: ./assets/rclone@.service
        dst: /usr/lib/systemd/user/rclone@.service
      - src: ./assets/google_drive_opener.py
        dst: /usr/share/nautilus-python/extensions/google_drive_opener.py
      - src: ./assets/adfinis-rclone-mgr.desktop
        dst: /usr/share/applications/adfinis-rclone-mgr.desktop
      - src: ./assets/adfinis-rclone-mgr.png
        dst: /usr/share/icons/hicolor/512x512/apps/adfinis-rclone-mgr.png
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /etc/bash_completion.d/{{ .ProjectName }}
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish
      - src: ./completions/{{ .ProjectName }}.zsh
        dst: /usr/share/zsh/site-functions/_{{ .ProjectName }}
    overrides:
      archlinux:
        dependencies:
          - python-nautilus
      deb:
        dependencies:
          - python3-nautilus

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Others
      order: 999
