---
name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install go-ctrf-json-reporter
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
      - name: Run tests
        run: go test -json ./... | go-ctrf-json-reporter -o test-results.json
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: test-results.json
          github-report: true
        if: always()
