---
name: test
on:
  push:
    branches:
      - main
      - v2
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0

        with:
          go-version-file: "go.mod"
          cache: true
      - name: Install go-ctrf-json-reporter
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
      - name: Run tests
        run: go test -json ./... | go-ctrf-json-reporter -o test-results.json
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@0f299074936c32ccaab5be5230511f6b2b9080aa # v1.0.28
        with:
          report-path: test-results.json
          github-report: true
        if: always()
